TC_ACL_2 and TC_ACL_3 are added
MERAprojects/ops pull request #5
Opened 2017-03-27 16:13 UTC by alulyan

Please leave comments or approve pull request

2017-03-27 19:24 UTC, AKochin requested changes
Looks good, but please remove unnecessary commented lines.

2017-03-27 19:25 UTC, AKochin submitted a review, later dismissed

2017-03-27 19:26 UTC, AKochin reviewed
Looks good, but please remove unnecessary commented lines.

2017-03-28 06:27 UTC, stroykov approved these changes

2017-03-28 14:54 UTC, alulyan commented
Hi, unnecessary commented lines are deleted

2017-03-28 15:18 UTC, AKochin approved these changes

2017-03-28 15:54 UTC, merged